filebeat.inputs:
  - type: container
    paths:
      - /var/log/containers/*.log
    processors:
      - add_kubernetes_metadata:
          host: ${NODE_NAME}
      - decode_json_fields:
          fields: ["message"]
          target: ""

output.elasticsearch:
  hosts: ["http://elasticsearch.logging.svc.cluster.local:9200"]
  index: "hrms-filebeat-%{+yyyy.MM.dd}"
